spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Kyrioscraft/ConfigRepository.git
          search-paths: CloudConfigStu
          username:
          password:
      label: master
  rabbitmq:
    host: 192.168.201.129
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone:  http://192.168.201.129:8761/eureka/
management:
  endpoint:
    bus-refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: bus-refresh

